### ISSUE TITLE
1.30 Serde Test failues

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#443] opened 2018-08-20 15:44 UTC
```
error[E0658]: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/log4rs-0.8.0/src/append/file.rs:25:1
   |
25 | #[serde(deny_unknown_fields)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error[E0658]: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/log4rs-0.8.0/src/append/console.rs:24:1
   |
24 | #[serde(deny_unknown_fields)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error[E0658]: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/log4rs-0.8.0/src/append/rolling_file/policy/compound/roll/delete.rs:16:1
   |
16 | #[serde(deny_unknown_fields)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error[E0658]: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/log4rs-0.8.0/src/append/rolling_file/policy/compound/roll/fixed_window.rs:17:1
   |
17 | #[serde(deny_unknown_fields)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error[E0658]: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/log4rs-0.8.0/src/append/rolling_file/policy/compound/trigger/size.rs:21:1
   |
21 | #[serde(deny_unknown_fields)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error[E0658]: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/log4rs-0.8.0/src/append/rolling_file/policy/compound/mod.rs:24:1
   |
24 | #[serde(deny_unknown_fields)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error[E0658]: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/log4rs-0.8.0/src/append/rolling_file/mod.rs:46:1
   |
46 | #[serde(deny_unknown_fields)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: aborting due to 7 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `log4rs`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by petrochenkov** [comment] 2018-08-20 15:48
Duplicate of https://github.com/rust-lang/rust/issues/53481

**Closed** 2018-08-21 17:29 UTC
